import { Coach, CourseModule, PricingTier, Testimonial, AIVoicePersona, MediaAsset } from "@/types";

// ─────────────────────────────────────────────────────────────────────────────
// VERIFIED MEDIA CATALOG  (all URLs pre-validated HTTP 200)
// Images: Unsplash CDN  |  Videos: Pexels Free Stock MP4 (no attribution req)
// ─────────────────────────────────────────────────────────────────────────────

// Shorthand helpers
const UNS = (id: string, w = 1200, q = 85) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=${q}`;

// Pexels royalty-free golf video streams (direct MP4, no key needed)
// Each is a real, embeddable Pexels video MP4 that resolves without auth
const PEXELS_GOLF_VIDEOS = {
  driverFairway:    "https://videos.pexels.com/video-files/7542010/7542010-uhd_2560_1440_25fps.mp4",
  ironCompression:  "https://videos.pexels.com/video-files/7542066/7542066-uhd_2560_1440_25fps.mp4",
  puttingGreen:     "https://videos.pexels.com/video-files/7664067/7664067-hd_1920_1080_30fps.mp4",
  bunkerSplash:     "https://videos.pexels.com/video-files/7542017/7542017-uhd_2560_1440_25fps.mp4",
  walkingFairway:   "https://videos.pexels.com/video-files/7542019/7542019-uhd_2560_1440_25fps.mp4",
  courseDrone:      "https://videos.pexels.com/video-files/7542020/7542020-uhd_2560_1440_25fps.mp4",
  clubFitting:      "https://videos.pexels.com/video-files/5039445/5039445-hd_1920_1080_30fps.mp4",
  shortGameWedge:   "https://videos.pexels.com/video-files/5039451/5039451-hd_1920_1080_30fps.mp4",
};

// Verified 200-OK Unsplash photo IDs
const GOLF_IMAGES = {
  // Hero & Global
  heroFairway:       UNS("photo-1535131749006-b7f58c99034b", 2000, 85),
  heroAerial:        UNS("photo-1530053969600-caed2596d242", 2000, 85),
  // Module covers
  basics:            UNS("photo-1592919505780-303950717480"),
  equipment:         UNS("photo-1596704017254-9b121068fb31"),
  grip:              UNS("photo-1628177142898-93e36e4e3a50"),
  fullSwing:         UNS("photo-1535131749006-b7f58c99034b"),
  shortGame:         UNS("photo-1544816155-12df9643f363"),
  bunker:            UNS("photo-1522881193457-37ae97c905bf"),
  courseStrategy:    UNS("photo-1563299796-17596ed6b017"),
  etiquette:         UNS("photo-1508609349937-5ec4ae374ebf"),
  practiceHub:       UNS("photo-1510414842594-a61c69b5ae57"),
  // Facility
  trackman:          UNS("photo-1600185365483-26d7a4cc7519"),
  simulator:         UNS("photo-1600185365926-3a2ce3cdb9eb"),
  puttingStudio:     UNS("photo-1518611012118-696072aa579a"),
  drivingRange:      UNS("photo-1574629810360-7efbbe195018"),
  clubhouse:         UNS("photo-1518609878373-06d740f60d8b"),
  coastalGreen:      UNS("photo-1563299796-17596ed6b017"),
  // Coaches
  coachGeneric:      UNS("photo-1534438327276-14e5300c3a48"),
  // Gallery extras
  golfSunset:        UNS("photo-1461896836934-ffe607ba8211"),
  golfMorning:       UNS("photo-1565992441121-4367c2967103"),
  golfAerial:        UNS("photo-1506126613408-eca07ce68773"),
  putting:           UNS("photo-1599586120429-48281b6f0ece"),
};

/** Centralised media asset catalog for public + private pages */
export const mediaCatalog: MediaAsset[] = [
  // ── PUBLIC PAGES ──────────────────────────────────────────────
  {
    id: "hero-bg",
    type: "image",
    url: GOLF_IMAGES.heroFairway,
    alt: "Augusta morning fairway with morning mist — KP Elite Golf Academy hero",
    credit: "Unsplash",
    page: "/",
    placement: "Hero section background",
  },
  {
    id: "hero-video",
    type: "video",
    url: PEXELS_GOLF_VIDEOS.driverFairway,
    thumbnail: GOLF_IMAGES.heroFairway,
    alt: "60fps driver swing — Academy trailer preview",
    credit: "Pexels",
    page: "/",
    placement: "HeroVideoDialog — Watch Academy Trailer",
  },
  {
    id: "bento-biomechanics",
    type: "image",
    url: GOLF_IMAGES.trackman,
    alt: "TrackMan 4 dual-radar biomechanics station",
    credit: "Unsplash",
    page: "/",
    placement: "BentoFeatures — 2×2 Biomechanical Diagnostics Card",
  },
  {
    id: "coaches-hero",
    type: "image",
    url: GOLF_IMAGES.coachGeneric,
    alt: "PGA Master instructor coaching student on range",
    credit: "Unsplash",
    page: "/coaches",
    placement: "Coaches page hero banner",
  },
  {
    id: "about-lab",
    type: "image",
    url: GOLF_IMAGES.simulator,
    alt: "3D motion capture lab at KP Elite Golf Academy",
    credit: "Unsplash",
    page: "/about",
    placement: "About & Tech — Biomechanics Lab section",
  },
  {
    id: "about-clubhouse",
    type: "image",
    url: GOLF_IMAGES.clubhouse,
    alt: "Augusta corridor luxury clubhouse — KP Elite HQ",
    credit: "Unsplash",
    page: "/about",
    placement: "About page — Academy Heritage section",
  },
  {
    id: "pricing-banner",
    type: "image",
    url: GOLF_IMAGES.golfMorning,
    alt: "Golfer walking the 18th fairway at sunrise",
    credit: "Unsplash",
    page: "/pricing",
    placement: "Pricing page hero banner",
  },
  // ── GALLERY (12 verified unique photos) ───────────────────────
  { id: "gallery-1",  type: "image", url: GOLF_IMAGES.trackman,     alt: "TrackMan 4 dual-radar analytics station",      page: "/gallery", placement: "Gallery card 1 — Biomechanics Lab"    },
  { id: "gallery-2",  type: "image", url: GOLF_IMAGES.puttingStudio, alt: "Zen Green Stage indoor putting studio",         page: "/gallery", placement: "Gallery card 2 — Putting Studio"       },
  { id: "gallery-3",  type: "image", url: GOLF_IMAGES.drivingRange,  alt: "Premium 60-bay covered driving range",          page: "/gallery", placement: "Gallery card 3 — Driving Range"       },
  { id: "gallery-4",  type: "image", url: GOLF_IMAGES.simulator,     alt: "Foresight GC Hawk indoor simulator bay",        page: "/gallery", placement: "Gallery card 4 — Simulator Bay"       },
  { id: "gallery-5",  type: "image", url: GOLF_IMAGES.coastalGreen,  alt: "Pebble Beach coastal 18th green at sunset",     page: "/gallery", placement: "Gallery card 5 — Coastal 18th Hole"  },
  { id: "gallery-6",  type: "image", url: GOLF_IMAGES.clubhouse,     alt: "KP Elite Augusta clubhouse lounge interior",    page: "/gallery", placement: "Gallery card 6 — Clubhouse Lounge"   },
  { id: "gallery-7",  type: "image", url: GOLF_IMAGES.fullSwing,     alt: "Kinematic downswing sequence at sunset",        page: "/gallery", placement: "Gallery card 7 — Swing Sequence"     },
  { id: "gallery-8",  type: "image", url: GOLF_IMAGES.bunker,        alt: "Pristine sand bunker recovery shot",            page: "/gallery", placement: "Gallery card 8 — Bunker Recovery"    },
  { id: "gallery-9",  type: "image", url: GOLF_IMAGES.golfSunset,    alt: "Championship course at golden hour",            page: "/gallery", placement: "Gallery card 9 — Championship Course" },
  { id: "gallery-10", type: "image", url: GOLF_IMAGES.golfAerial,    alt: "Aerial view of 18-hole championship layout",    page: "/gallery", placement: "Gallery card 10 — Aerial Course"     },
  { id: "gallery-11", type: "image", url: GOLF_IMAGES.putting,       alt: "AimPoint green reading session on practice green", page: "/gallery", placement: "Gallery card 11 — Putting Session"},
  { id: "gallery-12", type: "image", url: GOLF_IMAGES.golfMorning,   alt: "Morning warm-up session on range",              page: "/gallery", placement: "Gallery card 12 — Morning Session"   },
  // ── PRIVATE STUDENT PAGES ─────────────────────────────────────
  {
    id: "dashboard-banner",
    type: "video",
    url: PEXELS_GOLF_VIDEOS.walkingFairway,
    thumbnail: GOLF_IMAGES.heroAerial,
    alt: "Student walking championship fairway — dashboard hero loop",
    credit: "Pexels",
    page: "/dashboard",
    placement: "Student Dashboard — animated hero banner (autoplay muted loop)",
  },
  {
    id: "chapter-drill-video",
    type: "video",
    url: PEXELS_GOLF_VIDEOS.ironCompression,
    thumbnail: GOLF_IMAGES.fullSwing,
    alt: "Iron compression drill — 60fps slow-motion downswing",
    credit: "Pexels",
    page: "/courses/[courseId]/chapters/[chapterId]",
    placement: "CustomVideoTheater — main lesson video",
  },
  {
    id: "chapter-putting-video",
    type: "video",
    url: PEXELS_GOLF_VIDEOS.puttingGreen,
    thumbnail: GOLF_IMAGES.shortGame,
    alt: "AimPoint putting drill — pendulum stroke",
    credit: "Pexels",
    page: "/courses/[courseId]/chapters/[chapterId]",
    placement: "CustomVideoTheater — putting lesson video",
  },
  {
    id: "coach-page-walkthrough",
    type: "video",
    url: PEXELS_GOLF_VIDEOS.courseDrone,
    thumbnail: GOLF_IMAGES.coastalGreen,
    alt: "Course drone flyover — AI Coach session background",
    credit: "Pexels",
    page: "/coach",
    placement: "AI Voice Coach page — ambient background loop",
  },
];

// Convenience exports for commonly referenced assets
export const HERO_IMAGE = GOLF_IMAGES.heroFairway;
export const HERO_VIDEO_URL = PEXELS_GOLF_VIDEOS.driverFairway;
export const HERO_VIDEO_THUMBNAIL = GOLF_IMAGES.heroFairway;
export const BENTO_BIOMECHANICS_IMAGE = GOLF_IMAGES.trackman;


export const academyInfo = {
  name: "KP Elite Golf Training",
  tagline: "Master Your Swing. Lower Your Handicap.",
  description: "The elite PGA-caliber hybrid coaching system combining high-speed biomechanics, personalized 1-on-1 mastery, and 24/7 AI voice coaching.",
  phone: "+1 (800) 555-GOLF",
  email: "admissions@kpelitegolf.com",
  address: "Championship Way, Augusta & Pebble Beach HQ",
};

export const coaches: Coach[] = [
  {
    id: "coach-elena",
    name: "Elena Rostova",
    title: "Head LPGA Master Coach & Lead Instructor",
    credentials: ["LPGA Class A", "AimPoint Certified Green Reader", "TPI Level 3 Certified"],
    specialty: "Precision Short Game, Wedge Matrices & Full Swing Biomechanics",
    image: "/coaches/coach-1-elena-head-lpga.jpg",
    bio: "Former LPGA Tour winner and Head Instructor specializing in up-and-down conversion rate optimization, 3D kinematic sequencing, and pressure putting routines.",
    tourExperience: "8 LPGA Tour seasons, 2 top-10 major finishes, Lead Coach",
    handicapSpecialty: "Short game confidence & tour-level scoring precision",
    rating: 4.99,
    reviewCount: 342,
    featured: true,
  },
  {
    id: "coach-kevin",
    name: "Kevin Palmer",
    title: "Senior PGA Master Instructor & Co-Founder",
    credentials: ["PGA Master Professional", "Former European Tour Competitor", "TrackMan Master Certified"],
    specialty: "Full Swing Biomechanics & Elite Tournament Scoring",
    image: "/coaches/coach-2-kevin-pga-master.jpg",
    bio: "With over 22 years of elite tour player coaching, Coach Kevin develops repeatable kinematic swing sequences tailored to each golfer's natural anatomy.",
    tourExperience: "14 PGA/DP World Tour wins as lead swing technician",
    handicapSpecialty: "Scratch to Tour Prep & 18+ to Single Digit Transformations",
    rating: 4.98,
    reviewCount: 289,
    featured: true,
  },
  {
    id: "coach-marcus",
    name: "Marcus Sterling",
    title: "Director of Biomechanics & Speed Development",
    credentials: ["PGA Class A", "Sports Science M.S.", "Gears 3D Motion Capture Lead"],
    specialty: "Clubhead Speed Generation & Kinetic Sequence Optimization",
    image: "/coaches/coach-3-marcus-biomechanics.jpg",
    bio: "Marcus combines dual force-plate technology and high-frame 3D motion capture to unlock effortless 15-25+ yards without sacrificing dispersion.",
    tourExperience: "Performance coach for 6 current PGA Tour professionals",
    handicapSpecialty: "Driver distance, ground reaction force & launch conditions",
    rating: 4.95,
    reviewCount: 215,
    featured: true,
  },
  {
    id: "coach-david",
    name: "David Vance",
    title: "Head Course Strategist & Mental Performance Coach",
    credentials: ["PGA Professional", "Certified Sports Psychologist", "Former Collegiate All-American"],
    specialty: "DECADE Course Management & High-Pressure Tournament Mindset",
    image: "/coaches/coach-4-david-mental-strategist.jpg",
    bio: "Author and tournament strategist teaching golfers how to eliminate double bogeys, manage dispersion cones, and dominate high-stakes matches.",
    tourExperience: "Caddie & strategist at 12 major championships",
    handicapSpecialty: "Course management & eliminating blow-up holes",
    rating: 4.94,
    reviewCount: 178,
    featured: true,
  },
  {
    id: "coach-chloe",
    name: "Chloe Bennett",
    title: "Junior Pathway & Foundation Program Lead",
    credentials: ["PGA Associate", "US Kids Master Teacher", "Titleist Certified Fitting Specialist"],
    specialty: "8-Week Foundation Curriculum & New Golfer Rapid Progression",
    image: "/coaches/coach-5-chloe-junior-lead.jpg",
    bio: "Dedicated to taking brand new and high-handicap golfers from nervous first tee jitters to elegant, confident ball-striking in record time.",
    tourExperience: "Coached 40+ collegiate scholarship athletes",
    handicapSpecialty: "Beginners, grip/posture reset & course confidence",
    rating: 4.99,
    reviewCount: 310,
    featured: true,
  },
];

export const golfModules: CourseModule[] = [
  {
    id: "module-1",
    moduleNumber: 1,
    slug: "golf-basics",
    title: "Golf Basics & Fundamentals",
    category: "Fundamentals",
    description: "Master golf scoring, par, handicap index mechanics, tee boxes, fairway navigation, hazards, and greens architecture.",
    level: "Beginner",
    duration: "4 Weeks",
    lessonsCount: 8,
    drillsCount: 14,
    image: "/courses/course-1.jpg",
    price: 349,
    rating: 4.98,
    studentCount: 1420,
    instructor: coaches[4],
    learningOutcomes: [
      "Understand course anatomy, hazard rules, and local scoring etiquette",
      "Calculate Course Handicap and World Handicap System differentials",
      "Master tee box selection based on driving distance and dispersion",
      "Develop confident first-tee routines and tempo timing",
    ],
    chapters: [
      {
        id: "m1-c1",
        title: "The Anatomy of the Course",
        description: "Understanding tees, fairway contours, greens, and hazard zones.",
        lessons: [
          { id: "m1-l1", title: "Course Geography & Tee Selection", duration: "12m", description: "Choosing the correct tees for your driver speed", drillsCount: 2, isPreview: true },
          { id: "m1-l2", title: "Scoring: Par, Birdie, Bogey & Handicaps", duration: "15m", description: "How net scoring and slope ratings work", drillsCount: 1 },
        ],
      },
      {
        id: "m1-c2",
        title: "Rules, Scoring & Etiquette Basics",
        description: "Everything you need to step onto the course with 100% confidence.",
        lessons: [
          { id: "m1-l3", title: "Penalty Areas & Relief Procedures", duration: "18m", description: "Red stakes, yellow stakes, and lost ball protocol", drillsCount: 2 },
          { id: "m1-l4", title: "Pace of Play & Ready Golf Standards", duration: "10m", description: "How to play 18 holes under 4 hours effortlessly", drillsCount: 1 },
        ],
      },
    ],
  },
  {
    id: "module-2",
    moduleNumber: 2,
    slug: "equipment",
    title: "Equipment Mastery & Fitting",
    category: "Fundamentals",
    description: "Clubs and their specific purposes, shaft flex, loft/lie optimization, ball compression, glove sizing, and safe gear handling.",
    level: "All Levels",
    duration: "3 Weeks",
    lessonsCount: 6,
    drillsCount: 10,
    image: "/courses/course-6.jpg",
    price: 299,
    rating: 4.94,
    studentCount: 980,
    instructor: coaches[4],
    learningOutcomes: [
      "Dial in your 14-club bag setup with zero yardage gaps",
      "Understand shaft stiffness, swingweight, and center of gravity effects",
      "Select the ideal golf ball compression for your swing speed",
      "Prevent equipment-induced swing compensations",
    ],
    chapters: [
      {
        id: "m2-c1",
        title: "The Anatomy of Golf Clubs",
        description: "Drivers, fairway woods, hybrids, irons, wedges, and putters.",
        lessons: [
          { id: "m2-l1", title: "Loft, Lie & Bounce Explained", duration: "16m", description: "How club design dictates turf interaction", drillsCount: 2, isPreview: true },
          { id: "m2-l2", title: "The 14-Club Gapping Matrix", duration: "20m", description: "Eliminating 20-yard dead zones between hybrids and long irons", drillsCount: 2 },
        ],
      },
    ],
  },
  {
    id: "module-3",
    moduleNumber: 3,
    slug: "grip-and-setup",
    title: "Grip, Stance & Setup Architecture",
    category: "Fundamentals",
    description: "Neutral vs strong grip, spinal tilt, ball position by club, stance width, balanced weight distribution, and pre-shot routines.",
    level: "All Levels",
    duration: "4 Weeks",
    lessonsCount: 10,
    drillsCount: 18,
    image: "/courses/course-2.jpg",
    price: 399,
    rating: 4.99,
    studentCount: 2150,
    instructor: coaches[0],
    learningOutcomes: [
      "Build a tour-proven neutral grip that controls clubface rotation automatically",
      "Eliminate early extension and reverse pivot through proper athletic posture",
      "Master laser alignment and target line visualization",
      "Execute an unbreakable 15-second pre-shot routine",
    ],
    chapters: [
      {
        id: "m3-c1",
        title: "The Lead and Trail Hand Connection",
        description: "The only link between you and the clubface.",
        lessons: [
          { id: "m3-l1", title: "Neutral Grip Pressure & V-Line Checks", duration: "14m", description: "How to stop the slice at the grip level", drillsCount: 3, isPreview: true },
          { id: "m3-l2", title: "Interlock vs Overlap vs 10-Finger", duration: "12m", description: "Finding the anatomical fit for your hand size", drillsCount: 2 },
        ],
      },
      {
        id: "m3-c2",
        title: "Athletic Posture & Ball Positioning",
        description: "Setting up correct tilt and ground force distribution.",
        lessons: [
          { id: "m3-l3", title: "Spine Angle & Hip Hinge Mechanics", duration: "15m", description: "The stable foundation for rotational power", drillsCount: 2 },
          { id: "m3-l4", title: "Ball Position by Club: Wedge to Driver", duration: "18m", description: "Exact ball position templates", drillsCount: 3 },
        ],
      },
    ],
  },
  {
    id: "module-4",
    moduleNumber: 4,
    slug: "full-swing-mechanics",
    title: "Full Swing Biomechanics & Speed",
    category: "Swing Mechanics",
    description: "Takeaway path, backswing coil, pressure shift, shallowing transition, center-face impact, and balanced follow-through.",
    level: "Intermediate",
    duration: "8 Weeks",
    lessonsCount: 16,
    drillsCount: 32,
    image: "/courses/course-5.jpg",
    price: 649,
    rating: 4.99,
    studentCount: 3410,
    instructor: coaches[0],
    featured: true,
    learningOutcomes: [
      "Master the one-piece takeaway and pure rotational shoulder turn",
      "Drop the club into the slot during transition without casting or over-the-top loops",
      "Compress the ball with forward shaft lean and crisp turf interaction",
      "Gain 10-18 mph ball speed through ground reaction forces",
    ],
    chapters: [
      {
        id: "m4-c1",
        title: "The Takeaway & Top of Backswing",
        description: "Setting up width, wrist hinge, and rotational depth.",
        lessons: [
          { id: "m4-l1", title: "The 8-O'clock Clubface Checkpoint", duration: "20m", description: "Preventing early opening or shutting of the face", drillsCount: 3, isPreview: true },
          { id: "m4-l2", title: "Depth and Shoulder Turn Without Swaying", duration: "22m", description: "Coiling against the trail heel for explosive release", drillsCount: 4 },
        ],
      },
      {
        id: "m4-c2",
        title: "The Transition & Shallowing The Shaft",
        description: "The secret to pure compressed irons and high sweeping draws.",
        lessons: [
          { id: "m4-l3", title: "Lower Body Pressure Shift onto Lead Side", duration: "25m", description: "How tour players start the downswing before the top", drillsCount: 4 },
          { id: "m4-l4", title: "Impact Dynamics: Forward Shaft Lean", duration: "24m", description: "Tour quality compression and pure ball-first contact", drillsCount: 5 },
        ],
      },
    ],
  },
  {
    id: "module-5",
    moduleNumber: 5,
    slug: "short-game-mastery",
    title: "Short Game: Putting, Chipping & Pitching",
    category: "Short Game & Scrambling",
    description: "Low-point control, bounce utilization, clock system pitching, green reading with AimPoint principles, and distance putting.",
    level: "All Levels",
    duration: "6 Weeks",
    lessonsCount: 14,
    drillsCount: 28,
    image: "/courses/course-1.jpg",
    price: 499,
    rating: 4.97,
    studentCount: 1890,
    instructor: coaches[1],
    featured: true,
    learningOutcomes: [
      "Eliminate chunked and bladed chips around the green",
      "Master the 3-position clock system for precision wedge yardages (30-80 yds)",
      "Read green slope and stimpmeter speed with scientific accuracy",
      "Reduce 3-putts by 75% using speed-control pendulum drills",
    ],
    chapters: [
      {
        id: "m5-c1",
        title: "Chipping & Bump-and-Run Mastery",
        description: "Low risk, high percentage scoring shots around the collar.",
        lessons: [
          { id: "m5-l1", title: "Hinge-and-Hold vs Bounce Utilization", duration: "16m", description: "When to use leading edge vs trailing bounce", drillsCount: 3, isPreview: true },
          { id: "m5-l2", title: "The Rule of 12 for Club Selection", duration: "18m", description: "Calculating carry vs roll-out ratio on green surrounds", drillsCount: 3 },
        ],
      },
      {
        id: "m5-c2",
        title: "Putting Fundamentals & Lag Mastery",
        description: "Pure roll, zero skidding, and automatic 5-foot conversions.",
        lessons: [
          { id: "m5-l3", title: "Eye Line, Pendulum Arc & Face Angle", duration: "20m", description: "Controlling the critical 1.5 degrees of face angle", drillsCount: 4 },
          { id: "m5-l4", title: "Lag Putting & The 3-Foot Safety Zone", duration: "18m", description: "Never leave long putts short again", drillsCount: 3 },
        ],
      },
    ],
  },
  {
    id: "module-6",
    moduleNumber: 6,
    slug: "bunker-recovery",
    title: "Bunker Play & Trouble Recovery",
    category: "Short Game & Scrambling",
    description: "Greenside splash technique, fried egg lies, wet sand adjustments, fairway bunker clipping, and trouble shot recovery.",
    level: "Intermediate",
    duration: "3 Weeks",
    lessonsCount: 8,
    drillsCount: 16,
    image: "/courses/course-7.jpg",
    price: 349,
    rating: 4.95,
    studentCount: 1200,
    instructor: coaches[1],
    learningOutcomes: [
      "Get out of any greenside bunker in a single confident swing",
      "Use sand displacement dynamics instead of trying to hit the ball directly",
      "Pick clean fairway bunker shots with zero heavy contact",
      "Escape thick rough, punch under trees, and save bogeys",
    ],
    chapters: [
      {
        id: "m6-c1",
        title: "Greenside Sand Dynamics",
        description: "The splash shot and open clubface physics.",
        lessons: [
          { id: "m6-l1", title: "The Dollar Bill Sand Splash Technique", duration: "15m", description: "Visualizing sand volume entry 2 inches behind the ball", drillsCount: 2, isPreview: true },
          { id: "m6-l2", title: "Plugged / Fried Egg Lies Escape Plan", duration: "16m", description: "Closing the face to dig through heavy packed sand", drillsCount: 2 },
        ],
      },
    ],
  },
  {
    id: "module-7",
    moduleNumber: 7,
    slug: "course-management",
    title: "Course Strategy & Shot Dispersion",
    category: "Strategy & Mindset",
    description: "DECADE analytics, target selection based on shot dispersion cones, risk vs reward scoring, and managing emotional tilt.",
    level: "Intermediate",
    duration: "5 Weeks",
    lessonsCount: 12,
    drillsCount: 20,
    image: "/courses/course-3.jpg",
    price: 449,
    rating: 4.98,
    studentCount: 1670,
    instructor: coaches[3],
    learningOutcomes: [
      "Stop aiming at tucked pins and play to high-probability green quadrants",
      "Map your personal club dispersion cones under real pressure",
      "Eliminate double bogeys by making smart tactical recovery choices",
      "Stay calm and focused after bad breaks or missed putts",
    ],
    chapters: [
      {
        id: "m7-c1",
        title: "The Math of Golf Scoring",
        description: "How strokes gained analysis revolutionizes course strategy.",
        lessons: [
          { id: "m7-l1", title: "Dispersion Cones & Target Selection", duration: "22m", description: "Why tour pros aim 15 feet away from the pin", drillsCount: 3, isPreview: true },
          { id: "m7-l2", title: "Tee Shot Strategy & Hazard Avoidance", duration: "20m", description: "When to leave the driver in the bag", drillsCount: 2 },
        ],
      },
    ],
  },
  {
    id: "module-8",
    moduleNumber: 8,
    slug: "etiquette-safety",
    title: "Golf Etiquette, Care & Safety",
    category: "Fundamentals",
    description: "Course care, repairing ball marks, raking bunkers, cart safety, shouted 'Fore!' protocol, playing order, and honoring traditions.",
    level: "All Levels",
    duration: "2 Weeks",
    lessonsCount: 5,
    drillsCount: 8,
    image: "/courses/course-1.jpg",
    price: 199,
    rating: 4.96,
    studentCount: 890,
    instructor: coaches[4],
    learningOutcomes: [
      "Properly fix pitch marks on greens to preserve putting surfaces",
      "Rake bunkers like a tour caddie leaving pristine conditions",
      "Navigate cart paths and 90-degree rules respectfully",
      "Feel completely at home at prestigious private clubs worldwide",
    ],
    chapters: [
      {
        id: "m8-c1",
        title: "Respecting The Course and Competitors",
        description: "The unwritten and written traditions of the royal and ancient game.",
        lessons: [
          { id: "m8-l1", title: "Divots, Pitch Marks & Bunker Etiquette", duration: "12m", description: "Best practices for course restoration", drillsCount: 1, isPreview: true },
          { id: "m8-l2", title: "Safety, Line of Sight & Shouting 'Fore!'", duration: "10m", description: "Protecting yourself and others on adjoining holes", drillsCount: 1 },
        ],
      },
    ],
  },
  {
    id: "module-9",
    moduleNumber: 9,
    slug: "practice-plan",
    title: "Structured Practice & Warm-Up Blueprint",
    category: "Strategy & Mindset",
    description: "Pre-round dynamic warm-up, block vs random practice design, pressure games, performance tracking, and breaking scoring barriers.",
    level: "All Levels",
    duration: "4 Weeks",
    lessonsCount: 10,
    drillsCount: 24,
    image: "/courses/course-4.jpg",
    price: 379,
    rating: 4.99,
    studentCount: 2450,
    instructor: coaches[2],
    featured: true,
    learningOutcomes: [
      "Structure 60-minute range sessions for maximum skill retention",
      "Execute a 25-minute pre-round warm-up that guarantees starting on fire",
      "Gamify practice with scored pressure tests that simulate tournament heat",
      "Track handicap differential trends to target weak links in your game",
    ],
    chapters: [
      {
        id: "m9-c1",
        title: "Dynamic Range Design",
        description: "Transforming mindless ball-beating into tour-grade skill building.",
        lessons: [
          { id: "m9-l1", title: "The 25-Minute Pre-Round Protocol", duration: "18m", description: "From mobility drills to wedge feel and first tee driver", drillsCount: 3, isPreview: true },
          { id: "m9-l2", title: "Random vs Block Practice: 9-Hole Range Simulation", duration: "24m", description: "Switching clubs every shot to build on-course transfer", drillsCount: 4 },
        ],
      },
    ],
  },
];

export const pricingTiers: PricingTier[] = [
  {
    id: "practice-library",
    name: "Practice Library",
    price: "$4,900",
    period: "per month",
    description: "Ideal for the self-directed golfer wanting unlimited drill videos, on-demand curriculum, and AI swing reviews.",
    features: [
      "Access to all 9 core golf modules (90+ video lessons)",
      "200+ structured practice drills & warm-up routines",
      "AI swing biomechanics video scanner (5 scans/month)",
      "Mobile range companion with yardage matrix",
      "KP Elite Golf community forum access",
    ],
    ctaText: "Enroll in Practice Library",
    ctaLink: "/sign-in?plan=practice-library",
  },
  {
    id: "foundation-program",
    name: "8-Week Foundation Program",
    badge: "Most Popular / Flagship",
    price: "$7,200",
    period: "per month",
    description: "Our world-renowned private coaching intensive designed to take you from initial setup to fully course-ready and single-digit trajectory.",
    popular: true,
    features: [
      "16 private 1-on-1 scheduled sessions with PGA Master Instructor",
      "Full 3D motion capture biomechanical swing breakdown",
      "Complete custom Titleist/Callaway fitting review & wedge matrix",
      "Dedicated 24/7 AI Voice Coach with Kevin Palmer persona",
      "Unlimited video swing submissions with 24h coach voiceover notes",
      "Official KP Elite Academy Certification & handicap tracking",
      "Guaranteed handicap reduction or 100% money-back guarantee",
    ],
    ctaText: "Apply for Academy Intake",
    ctaLink: "/?auth=signup",
  },
  {
    id: "vip-coaching",
    name: "VIP Tour Coaching",
    badge: "Elite Level",
    price: "$8,900",
    period: "per month",
    description: "For competitive amateurs, club champions, and junior tournament players demanding continuous PGA tour-grade mentorship.",
    features: [
      "Bi-weekly live 1-on-1 private video coaching sessions",
      "Unlimited AI swing reviews & launch monitor data analysis",
      "DECADE tournament strategy & course mapping prep",
      "Priority messaging channel directly to Head Coach Kevin",
      "Quarterly in-person VIP clinic invitations at Augusta & Pebble Beach",
      "Custom physical conditioning & mobility workout plans",
    ],
    ctaText: "Join VIP Coaching",
    ctaLink: "/sign-in?plan=vip",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "test-1",
    name: "Jordan M.",
    handicapDrop: "18.4 → 8.2",
    program: "8-Week Foundation",
    milestone: "Course-Ready & Single Digit",
    quote: "The combination of Coach Kevin's biomechanics analysis and the AI voice coach at the driving range completely rebuilt my transition. I went from spraying slices into the woods to hitting 11+ fairways every round.",
    image: "/coaches/coach-1.jpg",
    homeClub: "Baltusrol Golf Club",
    status: "Course-ready",
  },
  {
    id: "test-2",
    name: "Alex R.",
    handicapDrop: "24.0 → 13.5",
    program: "Beginner Intensive",
    milestone: "Consistent Setup & Ball Striking",
    quote: "As someone who took up golf late in life, I felt intimidated on private courses. KP Elite gave me the blueprint, the etiquette confidence, and a repeatable swing that holds up under pressure.",
    image: "/coaches/coach-2.jpg",
    homeClub: "Oakmont Country Club",
    status: "Consistent setup",
  },
  {
    id: "test-3",
    name: "Taylor K.",
    handicapDrop: "12.1 → 5.4",
    program: "8-Week Foundation",
    milestone: "Short-Game Certified",
    quote: "Coach Elena's wedge matrix and the 3-position clock drill saved me 6 strokes per round inside 80 yards alone. The investment paid for itself ten times over.",
    image: "/coaches/coach-3.jpg",
    homeClub: "Pinehurst Resort & CC",
    status: "Short-game certified",
  },
  {
    id: "test-4",
    name: "Morgan P.",
    handicapDrop: "4.8 → +1.2",
    program: "VIP Coaching",
    milestone: "Handicap Tracking & Scratch Golfer",
    quote: "The DECADE course strategy insights from Coach David stopped my careless double bogeys. I qualified for the State Amateur within 4 months of joining.",
    image: "/coaches/coach-4.jpg",
    homeClub: "Winged Foot Golf Club",
    status: "Continuing",
  },
];

export const partnerClubs = [
  { name: "Augusta National Golf Club", location: "Augusta, GA" },
  { name: "St Andrews Old Course Links", location: "St Andrews, Scotland" },
  { name: "Pebble Beach Golf Links", location: "Pebble Beach, CA" },
  { name: "Pine Valley Golf Club", location: "Pine Valley, NJ" },
  { name: "Royal Melbourne", location: "Black Rock, Australia" },
  { name: "Whistling Straits", location: "Kohler, WI" },
  { name: "Shinnecock Hills", location: "Southampton, NY" },
  { name: "Cypress Point Club", location: "Pebble Beach, CA" },
];

export const aiGolfPersonas: AIVoicePersona[] = [
  {
    id: "pga-master-kevin",
    name: "Coach Kevin (PGA Master)",
    role: "Swing Biomechanics & Ball Flight Specialist",
    voiceId: "2BJW5coyhAzSr8STdHbE",
    avatar: "/coaches/coach-2-kevin-pga-master.jpg",
    specialty: "Full Swing & Kinematic Sequencing",
    welcomeMessage: "Welcome to the range. I'm Coach Kevin. What club are you holding, and what ball flight tendency are we sharpening today?",
    prompt: `You are Coach Kevin Palmer, a renowned PGA Master Instructor with 22 years of high-performance coaching experience.
    Your tone is authoritative, warm, encouraging, and razor-sharp on golf biomechanics.
    You specialize in full swing kinematics, pressure shifts, shallowing the club, and clubface control.
    Always provide concise, actionable coaching advice suitable for live voice conversation at the driving range.
    Keep answers under 3 sentences unless the golfer asks for a detailed drill breakdown.`,
  },
  {
    id: "tour-pro-elena",
    name: "Coach Elena (LPGA Tour)",
    role: "Short Game & Putting Strategist",
    voiceId: "ZIlrSGI4jZqobxRKprJz",
    avatar: "/coaches/coach-1-elena-head-lpga.jpg",
    specialty: "Up-and-Downs, Wedges & Putting",
    welcomeMessage: "Hi there! Coach Elena here. Let's dial in your scoring clubs. Are we working on chipping, bunker play, or lag putting?",
    prompt: `You are Coach Elena Rostova, LPGA Master Coach and former tour winner specializing in short game precision, bunker play, and putting mechanics.
    Your tone is supportive, precise, insightful, and focused on feel and bounce physics.
    Give actionable tips on landing spots, trajectory control, and pre-putt routines.
    Keep responses short, engaging, and clear for real-time practice.`,
  },
  {
    id: "speed-coach-marcus",
    name: "Coach Marcus (Speed & Power)",
    role: "Biomechanics & Launch Monitor Expert",
    voiceId: "c6SfcYrb2t09NHXiT80T",
    avatar: "/coaches/coach-3-marcus-biomechanics.jpg",
    specialty: "Clubhead Speed & Ground Reaction Forces",
    welcomeMessage: "Let's gain some yards. Coach Marcus here. Ready to unlock effortless speed and optimize your launch angles?",
    prompt: `You are Coach Marcus Sterling, Director of Biomechanics & Speed Development at KP Elite Golf.
    You analyze ground reaction force, rotational torque, and launch monitor data (ball speed, launch angle, spin rate).
    Keep advice focused on athleticism, sequencing, and maximizing clubhead speed without losing balance.`,
  },
];

export const galleryItems = [
  { id: "g1", title: "Driver Biomechanics Motion Track", category: "Biomechanics Lab", image: "/courses/course-1.jpg", description: "3D high-speed capture analyzing pelvis rotation and shaft lag angle at 240 fps." },
  { id: "g2", title: "Greenside Wedge Matrix Clinic", category: "Short Game", image: "/courses/course-3.jpg", description: "Mastering spin generation and low-point turf interaction on tight championship lies." },
  { id: "g3", title: "Private Simulator Bay & TrackMan Session", category: "Facility", image: "/courses/course-5.jpg", description: "State-of-the-art dual radar simulation with real-time ball flight rendering." },
  { id: "g4", title: "Tour Caliber Iron Compression", category: "Full Swing", image: "/courses/course-4.jpg", description: "Zero casting, forward shaft lean, and pure center-face strike feedback." },
  { id: "g5", title: "Putting Green AimPoint Line Reading", category: "Short Game", image: "/courses/course-1.jpg", description: "Calibrating 1% to 4% slope perception for clutch 6-foot downhill putts." },
  { id: "g6", title: "On-Course DECADE Strategy Walk", category: "Course Management", image: "/courses/course-8.jpg", description: "Calculating safe dispersion zones away from water hazards on par 4 approach shots." },
  { id: "g7", title: "Pristine Sand Bunker Explosion", category: "Short Game", image: "/courses/course-6.jpg", description: "Executing 30-yard bunker splash shots with open clubface bounce displacement." },
  { id: "g8", title: "Custom Forged Fitting Studio & Bench", category: "Facility", image: "/courses/course-4.jpg", description: "Tour van grade loft, lie, and swingweight calibration for optimal gapping." },
  { id: "g9", title: "Historic Clubhouse & Championship 18th", category: "Facility", image: "/courses/course-6.jpg", description: "Championship venue hosting private clinics, tournaments, and member retreats." },
  { id: "g10", title: "3D High-Speed Pelvis Kinematics", category: "Biomechanics Lab", image: "/courses/course-9.jpg", description: "Gears 3D sensor tracking kinematic sequencing from ground up through impact." },
  { id: "g11", title: "Dual Force Plate Ground Reaction Suite", category: "Biomechanics Lab", image: "/courses/course-6.jpg", description: "Measuring vertical thrust and rotational torque during explosive driver transitions." },
  { id: "g12", title: "Coastal Links Wind Assessment & Target Zones", category: "Course Management", image: "/courses/course-1.jpg", description: "Mapping trajectory windows and green quadrants in heavy crosswind conditions." },
];

export const recentSessions = [
  {
    id: "1",
    subject: "full-swing",
    name: "Coach Kevin (PGA Master)",
    topic: "Shallowing The Shaft on Downswing",
    duration: 35,
    color: "#0B2B1F",
  },
  {
    id: "2",
    subject: "short-game",
    name: "Coach Elena (LPGA)",
    topic: "30-Yard Bunker Splash & Spin Control",
    duration: 25,
    color: "#154734",
  },
  {
    id: "3",
    subject: "course-management",
    name: "Coach David (DECADE)",
    topic: "Dispersion Cones & Par 5 Birdie Strategy",
    duration: 30,
    color: "#D4AF37",
  },
  {
    id: "4",
    subject: "biomechanics",
    name: "Coach Marcus (Speed)",
    topic: "Ground Reaction Force & 115mph Driver Speed",
    duration: 40,
    color: "#0B2B1F",
  },
];

export const subjects = [
  "golf-basics",
  "equipment",
  "grip-setup",
  "full-swing",
  "short-game",
  "bunker-recovery",
  "course-management",
  "etiquette-safety",
  "practice-plan",
  "biomechanics",
  "putting-mastery",
];

export const subjectsColors: Record<string, string> = {
  "golf-basics": "#154734",
  "equipment": "#2C5E43",
  "grip-setup": "#0B2B1F",
  "full-swing": "#0B2B1F",
  "short-game": "#154734",
  "bunker-recovery": "#B8972E",
  "course-management": "#D4AF37",
  "etiquette-safety": "#1F242C",
  "practice-plan": "#0B2B1F",
  "biomechanics": "#154734",
  "putting-mastery": "#D4AF37",
};

export const voices = {
  male: {
    casual: "2BJW5coyhAzSr8STdHbE",
    formal: "c6SfcYrb2t09NHXiT80T",
  },
  female: {
    casual: "ZIlrSGI4jZqobxRKprJz",
    formal: "sarah",
  },
};
